v=input("Digite algo. ")
print("O tipo primitivo desse valor é. \n", type(v))
print("\n Só tem espaços? {}".format(v.isspace()))
print("\n É um número {}".format(v.isnumeric()))
print("\n É alfabético? {}".format(v.isalpha()))
print("\n É alfanumérico? {}".format(v.isalnum()))
print("\n Esta em minúsculas? {}".format(v.isupper()))
print("\n Está em maiúsculas {}".format(v. islower()))
print("\n É capitalizado {}".format(v.istitle()))